export { default as Home } from "../Pages/Home";
export { default as Details } from "../Pages/Details";
export { default as Discovery } from "../Pages/Discovery";
export { default as Upcoming } from "../Pages/Upcoming";
export { default as Favourite } from "../Pages/Favourite";
export { default as NowPlaying } from "../Pages/NowPlaying";
export { default as SearchMovies } from "../Pages/SearchMovies";
export { default as TopRated } from "../Pages/TopRated";
export { default as WatchLater } from "../Pages/WatchLater";
